### ISSUE TITLE
Dummy image URLs in unit tests cause console errors

### ISSUE THREAD

**Issue by sathomas** [sathomas/STEM#32]
Not really a functional issue, but the dummy URLs used for images in some of the unit tests cause console errors when the unit tests are run in the browser (`grunt serve:test`). We should replace the dummy image URLs with links to actual images (e.g. a Georgia Tech logo from `www.gatech.edu`) to eliminate the error messages that may obscure actual errors. Easiest way to see the errors is to look at the console during a unit test.

**Comment by jcarroll2007** [comment]
Hey Stephen, can we close this issue? As per https://github.com/sathomas/STEM/pull/39

**Comment by sathomas** [comment]
Suggest moving this issue to https://github.com/Georgia-STEM-Incubator/STEM if it's still desirable
