### ISSUE TITLE
Development Processes 

### ISSUE THREAD

**Issue by jcarroll2007** [sathomas/STEM#33]
Is it ok to create new branches to target each of the issues?

**Comment by sathomas** [comment]
Probably best approach is to fork the repo to your own account. Then submit pull requests from whatever branch you find convenient in your own repo against the main repo. Note also, that the branch to work against is [rc1](https://github.com/sathomas/STEM/tree/rc1) _not_ master.

**Comment by jcarroll2007** [comment]
Ok, got it. Thanks.
