### ISSUE TITLE
Unit tests for high level models very sparse

### ISSUE THREAD

**Issue by sathomas** [sathomas/STEM#34]
Even though we've got 100% code coverage, the unit tests for the high level models, e.g. [partners](https://github.com/sathomas/STEM/blob/rc1/app/scripts/models/partners.js) and [teacherSearch](https://github.com/sathomas/STEM/blob/rc1/app/scripts/models/teacherSearch.js), aren't currently testing a lot of the models' functionality. Additional unit tests should be added to better validate the model code.

**Comment by jcarroll2007** [comment]
Looking into this now.

**Comment by jcarroll2007** [comment]
Stephen, just wanted to let you know that I'm back to focusing on this issue. I'll continue to familiarize myself with the tests and models. If there is a higher priority task that you need completed, let me know!

Thanks.

**Comment by sathomas** [comment]
Turns out that there wasn't a lot more to add. I've taken care of this
