### ISSUE TITLE
Nav bar navigation

### ISSUE THREAD

**Issue by jcarroll2007** [sathomas/STEM#36]
Clicking on administrators targets URL `#schools`. Should this be `#administrators`? 

[Index.html Line 144](https://github.com/sathomas/STEM/blob/master/app/index.html#L142)

**Comment by sathomas** [comment]
Yep. Timely catch. The administrators section is just filler for now. I'm starting the design this afternoon.

**Comment by sathomas** [comment]
Fixed this in RC1
