### ISSUE TITLE
Prepare for possible IE9 support

### ISSUE THREAD

**Issue by sathomas** [sathomas/STEM#51]
Once the site is launched, demographic data (or requests/complaints) about our users may suggest we rethink the decision not to support IE9. In preparation for that possibility, we should map out a plan for supporting IE9. Two known issues are #29 and #31, though there may be others.
1. Thorough test with IE9 to look for other potential problems.
2. Provide CSS fallback styles for non flexbox support (e.g. resurrect #31).
3. Propose and test solutions for CORS workarounds (e.g. resurrect #29).
4. Propose and test solutions for other problems uncovered in step 1.

**Comment by sathomas** [comment]
Note: It's not certain that we'll need to implement any of the code from this issue. We may find that our IE9 user base isn't significant. But we'd like to have the code ready to go if it does become important.

**Comment by jcarroll2007** [comment]
Just listing this here (although it is pretty obvious):

The detailed text in the discovery nav overflows in IE10/11

**Comment by sathomas** [comment]
@jcarroll2007 can you include a screen shot? I'm not seeing any overflow on IE11, but I'm running via remote desktop, so that may be throwing it off.

**Comment by jcarroll2007** [comment]
![image](https://cloud.githubusercontent.com/assets/8485105/7418844/03673a28-ef3f-11e4-99d0-ac50478fa823.png)

**Comment by sathomas** [comment]
@jcarroll2007 is that from the production site? Using IE11? or is this something you're seeing in your local branch modified for IE9. Here's what I see on production in IE11:

![screen shot 2015-04-30 at 1 47 32 pm](https://cloud.githubusercontent.com/assets/1731910/7418945/b33ea242-ef3f-11e4-8d90-eb27b92e0ada.png)

**Comment by jcarroll2007** [comment]
@sathomas Hmm... I wonder why we are seeing different results. Here is another screenshot of the production site on IE11 (the previous screenshot was from a local branch).
![image](https://cloud.githubusercontent.com/assets/8485105/7419310/3a96ef0e-ef42-11e4-87a3-8fad5b4e18ee.png)

**Comment by sathomas** [comment]
@jcarroll2007 well that sucks. I'll create a separate ticket (#62) for the issue. Can you focus on debugging it for now? I'll also see if I can scare up another system that would let me reproduce it.

**Comment by jcarroll2007** [comment]
Sure thing. Looking into it now.

**Comment by sathomas** [comment]
@jcarroll2007 thx!

**Comment by jcarroll2007** [comment]
Another note for this ticket - we need to watch for nested media queries (which there are plenty of). These are unsupported in IE9.

Example:

``` (css)
Bad
.class {
    @media @desktop { // styles }
}

Good
@media @desktop {
    .class { // styles }
}
```

**Comment by sathomas** [comment]
Actually, unless things have changed recently, support for nested media queries is pretty lousy in most browsers, despite it being legitimate per CSS3. But @jcarroll2007 is confusing CSS with LESS. The LESS compiler takes care of the problem.

The fragment in `style.less`:

```
.class {
    // styles
    @media @desktop { // more styles }
}
```

is compiled to `styles.css` as:

```
.class {
    // styles
}
@media only screen and (min-width: 1000px) {
    .class {
        // more styles
    }
}
```

So there's nothing to worry about.

**Comment by jcarroll2007** [comment]
Oh ok! Great to know @sathomas. Thanks.

**Comment by sathomas** [comment]
Suggest moving this issue to https://github.com/Georgia-STEM-Incubator/STEM if it's still desirable
