### ISSUE TITLE
Unit tests for high level views

### ISSUE THREAD

**Issue by sathomas** [sathomas/STEM#53]
Current the high level views (`adminsAsDiscovery`, `discoveryAsContent`, `partnersAsDiscovery`, `posAsMap`, `teachersAsDiscovery`, and `teacherSearchAsPage`) lack unit tests. We should add unit tests for those views.

**Comment by jcarroll2007** [comment]
Do you want us to continue branching off of rc1?

**Comment by sathomas** [comment]
Yeah, I think we'll stick with `rc1` until the official launch

**Comment by gscoppino** [comment]
Working branch info (for reference): https://github.com/gscoppino/STEM/tree/STEM_52_unit_tests_for_high_level_views

**Comment by gscoppino** [comment]
...
~~In a test case for `PoisAsMap`, I'm attempting to add a `Poi` to a `Pois`, and expecting the DOM to update containing a new marker. However, this test fails as it is unable to find any markers in the DOM.~~
...

**Comment by gscoppino** [comment]
Disregard that last comment, checking the code coverage in the browser test made the problem fairly obvious. `setView` was never called internally due to lack of extra information.

**Comment by gscoppino** [comment]
When testing `partnersAsDiscovery` and `adminsAsDiscovery` with a simple empty element as the starting point (building the view from scratch), eg. `<article id="admins" class="discovery theme-2"></article>` the `render()` function will fail since it attempts to render the `PoisAsMap` views when the necessary `el`s do not exist yet. This could be fixed by just moving the `PoisAsMap` instantiations into the `render()` function, but I'm not sure that's a good idea. Thoughts?

**Comment by sathomas** [comment]
I'm still recovering from (minor) surgery, so I may not be thinking straight, but
- If you need a DOM element, you can insert a `$scaffolding` container in the page. There are some views that already do this, so that can give you a template.
- If it's not too challenging, it would be better to test the view independently of other views. To do that, you could use a sinon stub.

**Comment by gscoppino** [comment]
1. Got it, so I should just provide the elements it expects to see in the scaffolding. Thanks!
2. Understood, I have been avoiding doing so. I'm considering making more use of mocks as well.

**Comment by gscoppino** [comment]
A problem I keep coming back to try and solve concerns a listener for an event `set:searchQuery` (to be emanated  from the `teachers` model which has an attribute `searchQuery`. However, I don't see this event on the catalog of built in Backbone events: http://backbonejs.org/#Events-catalog and the source for `teachers.js` doesn't emanate the event manually. Here's the test source:

```
    it('After render, if the teachers model has its search model reset, the searchForm property of this view should be updated and re-rendered.', function() {
        this.TeachersAsDiscovery.remove();
        var functionSpy = sinon.spy(this.TeachersAsDiscovery, 'renderSearch');
        this.TeachersAsDiscovery.initialize(); // re-bind event handler to use spy.
        this.TeachersAsDiscovery.render();
        functionSpy.reset(); // render makes a call to renderSearch which we don't care for in this test.

        this.TeachersAsDiscovery.model.unset('searchQuery', { silent: true });
        var newQuery = new Stem.Models.Search({
            label: 'Test Label',
            placeholder: 'Test Placeholder'
        });
        this.TeachersAsDiscovery.model.set('searchQuery', newQuery);

        functionSpy.callCount.should.equal(1);
        this.TeachersAsDiscovery.searchForm.model.should.equal(newQuery);

        functionSpy.restore();
    });
```

The test fails by having a callCount of 0.

**Comment by sathomas** [comment]
Yeah, I think that's a bug in the code itself. Should be `'change:searchQuery'` instead of `'set:searchQuery'`

**Comment by sathomas** [comment]
The test code looks good BTW

**Comment by gscoppino** [comment]
Thanks! Making that change to the event listener fixes the problem, and does not break any other existing tests.

**Comment by gscoppino** [comment]
Different problem: When testing spotlights for `AdminsAsDiscovery` (new test for the change to spotlights you made recently), the template which builds `OaeAsSpotlightItem` will fail out if `picture` isn't defined. The reason for this is I put up a fake server which returns a response without a `picture` property. Should I give it a picture property, or should the possible lack of a source be handled in `OaeAsSpotlightItem`'s template. Here's the test I'm writing for reference:

```
    it('After render, if the spotlight list is populated, it should be shown.', function() {
        var baseUrl = Stem.config.oae.protocol + '//' + Stem.config.oae.host + '/api/group/';
        var groupUrl = new RegExp(baseUrl + '\d+');
        var subgroupUrl = new RegExp(baseUrl = '\d+/members$');
        var server = sinon.fakeServer.create()
        server.respondWith("GET", groupUrl, [200, { 'Content-Type': 'application/json'}, '{}']);
        server.respondWith("GET", subgroupUrl, [200, { 'Content-Type': 'application/json'}, '{}']);

        this.AdminsAsDiscovery.model.get('spotlights').add(new Stem.Models.Group());
        var $el = this.AdminsAsDiscovery.render().$el;
        $el.find('.spotlight-block').hasClass('util--hide').should.be.false();

        server.restore();
    });
```

The error below just for completeness' sake:

```
ReferenceError: picture is not defined
    at JST.app/scripts/templates/oaeAsSpotlightItem.ejs [as template] (http://localhost:9001/scripts/templates.js:87:26)
    at Stem.Views.OaeAsSpotlightItem.Backbone.View.extend.render (<anonymous>:60:20)
    at Stem.Views.OaeAsSpotlightList.Backbone.View.extend.add (<anonymous>:177:20)
    at http://localhost:9001/bower_components/underscore/underscore.js:73:21
    at Function._.each._.forEach (http://localhost:9001/bower_components/underscore/underscore.js:153:9)
    at _.each.Collection.(anonymous function) [as each] (http://localhost:9001/bower_components/backbone/backbone.js:966:24)
    at Stem.Views.OaeAsSpotlightList.Backbone.View.extend.render (<anonymous>:154:17)
    at Stem.Views.AdminsAsDiscovery.Backbone.View.extend.render (<anonymous>:165:16)
    at Context.<anonymous> (http://localhost:9001/views/adminsAsDiscovery.spec.js:58:42)
    at Test.require.register.Runnable.run (http://localhost:9001/bower_components/mocha/mocha.js:4263:32)
```

**Comment by gscoppino** [comment]
Problem went away. Probably was actually caused by me returning objects instead of arrays (doh!...). Terribly sorry about the confusion. Got the spotlight tests for `AdminsAsDiscovery` and `PartnersAsDiscovery` working and pushed. Here is what the above test looks like now:

```
    it('After render, if the spotlight list is populated, it should be shown.', function() {
        var baseUrl = Stem.config.oae.protocol + '//' + Stem.config.oae.host + '/api/group/';
        var subgroupUrl = new RegExp(baseUrl + '.+/members([?]limit=\d+)?');
        var server = sinon.fakeServer.create();
        server.respondImmediately = true;
        server.respondWith("GET", subgroupUrl, [
            200,
            { 'Content-Type': 'application/json' },
            JSON.stringify([{"profile":{}, "role": "test"}, {"profile":{ "resourceType": "group" }, "role": "test"}])
        ]);

        /* Reset test fixtures */
        this.Discovery = new Stem.Models.Discovery();
        server.respond();
        this.AdminsAsDiscovery = new Stem.Views.AdminsAsDiscovery({
            el: this.$Scaffolding.empty(),
            model: this.Discovery.get('admins')
        });

        var $el = this.AdminsAsDiscovery.render().$el;
        $el.find('.spotlight-block').hasClass('util--hide').should.be.false();

        server.restore();
    });
```

Next thing is to take a second pass at test structure, as you can see I ended up re-initializing data that was previously initialized in `beforeEach` here, need to re-structure.

**Comment by jcarroll2007** [comment]
Stephen: While working on discoveryAsContent, I came across something rather unexpected. First of all, - the article tags are not closed in the template. So, this causes rendering issues (I have fixed this on my branch). [discoveryAsContent.ejs](https://github.com/sathomas/STEM/blob/master/app/scripts/templates/discoveryAsContent.ejs)

Secondly, the template doesn't include [discovery-nav](https://github.com/sathomas/STEM/blob/master/app/index.html#L247) or the [landing-page-heading](https://github.com/sathomas/STEM/blob/master/app/index.html#L222). So, if the template were empty, neither of these would be present on the page. Is this desired or something that should be fixed?

**Comment by sathomas** [comment]
I wouldn't sweat the high-level templates too much. They're really only defined as a convenience for testing. The production app doesn't generate the page _de novo_ from templates. Instead, the initial `index.html` provides the basic "infrastructure" for the page. The JavaScript code then "fills in" the dynamic content where it's appropriate. This approach allows the page to work even for users that don't have JavaScript. (You can try it by disabling JavaScript in your browser and visiting the site.) Obviously, the full functionality isn't available, but the site is (supposed to be) still usable.

It wouldn't hurt to add the closing tags, but there's no need to add unnecessary elements to the templates.

**Comment by gscoppino** [comment]
Hey Stephen:

1) Both me and Jordan are having trouble with tests which involve triggering radio buttons in the browser. Jordan's problem is `DiscoveryAsContent` child view switching, while mine is `TeacherSearchAsPage` main view switching. Triggering DOM events simply does not invoke the view functions that are watching for them. I ran into a similar problem with checkboxes which I got working by triggering a `click` and a `change` event on the necessary elements, but this does not work for the radio buttons. This is the only thing blocking us from bringing all view coverage to 100%. We may just settle for triggering the events on the views/models manually if we can't find a solution to that. Any feedback is appreciated.

2) Cleaning up test outputs. I adopted a format for the views you assigned us that looks like this:
![for stephen stem tests](https://cloud.githubusercontent.com/assets/5316305/7635689/4f8f43ae-fa30-11e4-89b1-b5bb6d3af14d.png)
Would you mind if I formatted the other existing view tests you wrote to look like this?

**Comment by sathomas** [comment]
Suggest moving this issue to https://github.com/Georgia-STEM-Incubator/STEM if it's still desirable
