### ISSUE TITLE
Text overflows in discovery navigation on IE10/IE11

### ISSUE THREAD

**Issue by sathomas** [sathomas/STEM#62]

**Comment by jcarroll2007** [comment]
Looking into this now. It seems to be related to flexbox - working on a fix.

**Comment by sathomas** [comment]
Since I can't reproduce it (yet), I can't be sure, but it could be this [IE bug](https://connect.microsoft.com/IE/feedback/details/885663/flexbox-wrap-flex-items-in-ie11-broken). My IE11 instance may be pre-release (I can't tell) with the bug fixed. There are a couple of [stackoverflow](http://stackoverflow.com/questions/19138107/ie11-flexbox-preventing-text-wrapping) [questions](http://stackoverflow.com/questions/16808815/ie10-flexbox-p-element-non-wrapping) with possible workarounds.

**Comment by sathomas** [comment]
More [details](https://github.com/philipwalton/flexbugs#2-column-flex-items-set-to-align-itemscenter-overflow-their-container)

**Comment by jcarroll2007** [comment]
Thanks for that last link! That fixed the problem. Creating a PR in just a second.

**Comment by sathomas** [comment]
Sweet. BTW, if you haven't already done so, can you check the fix on IE10 as well. Thanks

**Comment by jcarroll2007** [comment]
Just checked - the fix works on 10 as well.
